pure pursuit
RIT-MDRC/mdrc-pacbot pull request #91
Opened 2024-10-22 17:48 UTC by Ben-RIT

2024-10-22 17:50 UTC, Ben-RIT commented
Made speed a constant at the top, but it could easily be changed to a parameter. Also, no acceleration limits which leads to pacbot overshooting the target in higher speed cases.

2024-10-22 23:20 UTC, MJE10 approved these changes
lgtm if build passes

2024-10-22 23:22 UTC, MJE10 requested changes

2024-10-22 23:22 UTC, MJE10 commented on server_pb/src/main.rs
> +                        .args(["run", "--bin", "sim_pb"])
pls put back

2024-10-23 02:07 UTC, MJE10 approved these changes

2024-10-23 02:35 UTC, merged